/*
 * This source file was generated by the Gradle 'init' task
 */
package discord;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class App {
    public static void main(String[] args) throws Exception {
        
        JDA api = JDABuilder.createDefault(Config.TOKEN).build();
    }
}
