/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */
 //Versions

val jdaVersion = "6.3.0"
val slf4jVersion = "2.0.13"
val logbackClassicVersion = "1.5.6"
val javaDotenvVersion = "5.2.2"
val lavaplayerVersion = "2.2.6"
val lavalinkYoutubeVersion = "1.18.0"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.3.0"
    id("com.github.ben-manes.versions") version "0.53.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    // Stupid lavalink
     maven(url = "https://maven.lavalink.dev/releases")
}

dependencies {
    implementation("club.minnced:jdave-api:0.1.5")

    implementation("club.minnced:jdave-native-linux-x86-64:0.1.5")
    implementation("club.minnced:jdave-native-linux-aarch64:0.1.5")
    implementation("club.minnced:jdave-native-win-x86-64:0.1.5")

    implementation("net.dv8tion:JDA:$jdaVersion")
    implementation("org.slf4j:slf4j-api:$slf4jVersion")
    implementation("ch.qos.logback:logback-classic:$logbackClassicVersion")
    implementation("io.github.cdimascio:java-dotenv:$javaDotenvVersion")
    implementation("dev.arbjerg:lavaplayer:$lavaplayerVersion")
    implementation("dev.lavalink.youtube:common:$lavalinkYoutubeVersion")
    implementation("org.reflections:reflections:0.10.2")

    implementation(platform("com.fasterxml.jackson:jackson-bom:2.17.0"))

    implementation("com.fasterxml.jackson.core:jackson-core")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.core:jackson-annotations")

    //DB
    implementation("org.xerial:sqlite-jdbc:3.51.2.0")
    }

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.isIncremental = true

    // Set this to the version of java you want to use,
    // the minimum required for JDA is 1.8
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "discord.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Mibamba solver
tasks.named<ProcessResources>("processResources") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}